[package]
name = "roottest"
version = "0.1.0"
authors = ["SuperCuber <amit.gold00@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.*"
crossterm = "0.19.0"
log = "0.4.*"
serde = {version = "1.*", features = ["derive"]}
simplelog = "0.9.*"
structopt = "0.3.*"
toml = "0.4.*"
